import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideIcons } from '@ng-icons/core';

import {
  lucideHome,
  lucideMenu,
  lucideLayoutDashboard,
  lucideCrown,
  lucideQrCode,
  lucideLogOut,
  lucideSettings,
  lucideUser,
  lucideCheck,
  lucideStore,
  lucideHandshake,
  lucideTriangleAlert,
  lucidePalette,
  lucideShare2,
  lucideMousePointerClick,
  lucideImages,
  lucideUpload,
  lucideInstagram,
  lucideFacebook,
  lucideMail,
  lucideCheckCircle,
  lucideTag,
  lucideCreditCard,
  lucideCalendar,
  lucideMapPin,
  lucideChevronDown,
  lucideEye,
  lucideEdit,
  lucideLoader2,
  lucidePhone,
  lucideFileText,
  lucideXCircle,
  lucideChevronRight,
  lucideChevronsRight,
  lucideChevronLeft,
  lucideChevronsLeft,
  lucidePlus,
  lucideRefreshCcw,
  lucideCopy,
  lucideContact,
  lucideLink,
  lucideLockKeyhole,
  lucideFileUser,
  lucideVideo,
  lucideYoutube,
  lucideDownload,
  lucideX,
  lucideArrowRight,
  lucideLock,
  lucideMailOpen,
  lucideInfo,
  lucideMessageSquare,
  lucideTruck,
} from '@ng-icons/lucide';

import { svglTiktok } from '@ng-icons/svgl';

import {
  bootstrapArrowLeft,
  bootstrapArrowRight,
  bootstrapArrowClockwise,
  bootstrapBox,
  bootstrapCalendarEvent,
  bootstrapCheck,
  bootstrapCheckCircle,
  bootstrapCheckCircleFill,
  bootstrapChevronDown,
  bootstrapClockHistory,
  bootstrapCloudUpload,
  bootstrapCreditCard,
  bootstrapCurrencyDollar,
  bootstrapExclamationTriangle,
  bootstrapFileEarmarkWordFill,
  bootstrapGraphUp,
  bootstrapHeadset,
  bootstrapHourglassSplit,
  bootstrapInfoCircle,
  bootstrapLink,
  bootstrapLinkedin,
  bootstrapLock,
  bootstrapLockFill,
  bootstrapMusicNoteBeamed,
  bootstrapPerson,
  bootstrapQuestionCircle,
  bootstrapReceipt,
  bootstrapShieldCheck,
  bootstrapShieldLock,
  bootstrapSpotify,
  bootstrapTelegram,
  bootstrapTicketPerforated,
  bootstrapTwitterX,
  bootstrapWhatsapp,
  bootstrapXCircle,
  bootstrapLightbulb,
} from '@ng-icons/bootstrap-icons';

import { monoClipboardCheck, monoCreditCard, monoPause } from '@ng-icons/mono-icons';

import { aspectsSocialFacebook, aspectsSocialYoutube } from '@ng-icons/ux-aspects';

import { dripWeb } from '@ng-icons/dripicons';

import { remixFeedbackLine, remixPixFill, remixSuitcase2Line } from '@ng-icons/remixicon';

import { provideNgxMask, provideEnvironmentNgxMask } from 'ngx-mask';

import { provideHttpClient, withInterceptors } from '@angular/common/http';

import { routes } from './app.routes';

import { authInterceptor } from './core/http/auth.interceptors';

import { provideCharts, withDefaultRegisterables } from 'ng2-charts';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),

    provideRouter(routes),

    provideIcons({
      lucideHome,
      lucideMenu,
      lucideLayoutDashboard,
      lucideCrown,
      lucideQrCode,
      lucideLogOut,
      lucideSettings,
      lucideUser,
      lucideCheck,
      lucideStore,
      lucideHandshake,
      lucideTriangleAlert,
      lucidePalette,
      lucideShare2,
      lucideMousePointerClick,
      lucideImages,
      lucideUpload,
      lucideInstagram,
      lucideFacebook,
      lucideMail,
      lucideCheckCircle,
      lucideTag,
      lucideCreditCard,
      lucideCalendar,
      lucideMapPin,
      lucideChevronDown,
      lucideEye,
      lucideEdit,
      lucideLoader2,
      lucidePhone,
      lucideFileText,
      lucideXCircle,
      lucideChevronRight,
      lucideChevronsRight,
      lucideChevronLeft,
      lucideChevronsLeft,
      lucidePlus,
      lucideRefreshCcw,
      lucideCopy,
      lucideContact,
      lucideLink,
      lucideLockKeyhole,
      lucideFileUser,
      lucideVideo,
      lucideYoutube,
      lucideDownload,
      lucideX,
      lucideArrowRight,
      lucideLock,
      lucideMailOpen,
      lucideInfo,
      lucideMessageSquare,
      svglTiktok,
      lucideTruck,
      bootstrapArrowLeft,
      bootstrapArrowRight,
      bootstrapArrowClockwise,
      bootstrapBox,
      bootstrapCalendarEvent,
      bootstrapCheck,
      bootstrapCheckCircle,
      bootstrapCheckCircleFill,
      bootstrapChevronDown,
      bootstrapClockHistory,
      bootstrapCloudUpload,
      bootstrapCreditCard,
      bootstrapCurrencyDollar,
      bootstrapExclamationTriangle,
      bootstrapFileEarmarkWordFill,
      bootstrapGraphUp,
      bootstrapHeadset,
      bootstrapHourglassSplit,
      bootstrapInfoCircle,
      bootstrapLink,
      bootstrapLinkedin,
      bootstrapLock,
      bootstrapLockFill,
      bootstrapMusicNoteBeamed,
      bootstrapPerson,
      bootstrapQuestionCircle,
      bootstrapReceipt,
      bootstrapShieldCheck,
      bootstrapShieldLock,
      bootstrapSpotify,
      bootstrapTelegram,
      bootstrapTicketPerforated,
      bootstrapTwitterX,
      bootstrapWhatsapp,
      bootstrapXCircle,
      bootstrapLightbulb,

      monoClipboardCheck,
      monoCreditCard,
      monoPause,

      aspectsSocialFacebook,
      aspectsSocialYoutube,

      dripWeb,

      remixFeedbackLine,
      remixPixFill,
      remixSuitcase2Line,
    }),

    provideEnvironmentNgxMask(),

    provideNgxMask(),

    provideHttpClient(withInterceptors([authInterceptor])),

    provideCharts(withDefaultRegisterables()),
  ],
};
