import { ApplicationConfig, provideBrowserGlobalErrorListeners } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideIcons } from '@ng-icons/core';

import {
  lucideHome,
  lucideMenu,
  lucideLayoutDashboard,
  lucideCrown,
  lucideQrCode,
  lucideLogOut,
  lucideSettings,
  lucideUser,
  lucideCheck,
  lucideStore,
  lucideHandshake,
  lucideTriangleAlert,
  lucidePalette,
  lucideShare2,
  lucideMousePointerClick,
  lucideImages,
  lucideUpload,
  lucideInstagram,
  lucideFacebook,
  lucideMail,
  lucideCheckCircle,
  lucideTag,
  lucideCreditCard,
  lucideCalendar,
  lucideMapPin,
  lucideChevronDown,
  lucideEye,
  lucideEdit,
  lucideLoader2,
  lucidePhone,
  lucideFileText,
  lucideXCircle,
  lucideChevronRight,
  lucideChevronsRight,
  lucideChevronLeft,
  lucideChevronsLeft,
  lucidePlus,
  lucideRefreshCcw,
  lucideCopy,
  lucideContact,
  lucideLink,
  lucideLockKeyhole,
  lucideFileUser,
  lucideVideo,
  lucideYoutube,
  lucideDownload,
} from '@ng-icons/lucide';

import { svglTiktok } from '@ng-icons/svgl';
import {
  bootstrapArrowLeft,
  bootstrapCheckCircleFill,
  bootstrapCloudUpload,
  bootstrapCurrencyDollar,
  bootstrapFileEarmarkWordFill,
  bootstrapGraphUp,
  bootstrapLink,
  bootstrapLinkedin,
  bootstrapLockFill,
  bootstrapMusicNoteBeamed,
  bootstrapSpotify,
  bootstrapTelegram,
  bootstrapTicketPerforated,
  bootstrapTwitterX,
  bootstrapWhatsapp,
} from '@ng-icons/bootstrap-icons';

import { monoClipboardCheck, monoCreditCard, monoPause } from '@ng-icons/mono-icons';
import { aspectsSocialFacebook, aspectsSocialYoutube } from '@ng-icons/ux-aspects';
import { dripWeb } from '@ng-icons/dripicons';
import { remixFeedbackLine, remixPixFill, remixSuitcase2Line } from '@ng-icons/remixicon';
import { provideNgxMask, provideEnvironmentNgxMask } from 'ngx-mask';
import { provideHttpClient, withInterceptors } from '@angular/common/http';

import { routes } from './app.routes';
import { authInterceptor } from './core/http/auth.interceptors';
import { provideCharts, withDefaultRegisterables } from 'ng2-charts';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),

    provideIcons({
      lucideHome,
      lucideMenu,
      lucideLayoutDashboard,
      lucideCrown,
      lucideQrCode,
      lucideLogOut,
      lucideSettings,
      lucideUser,
      lucideCheck,
      lucideStore,
      lucideHandshake,
      lucideTriangleAlert,
      lucidePalette,
      lucideShare2,
      lucideMousePointerClick,
      lucideImages,
      lucideUpload,
      lucideInstagram,
      svglTiktok,
      bootstrapLinkedin,
      bootstrapCurrencyDollar,
      lucideFacebook,
      aspectsSocialFacebook,
      aspectsSocialYoutube,
      bootstrapTelegram,
      lucideMail,
      bootstrapTwitterX,
      dripWeb,
      bootstrapSpotify,
      lucideCheckCircle,
      lucideTag,
      lucideCreditCard,
      lucideCalendar,
      lucideMapPin,
      lucideChevronDown,
      lucideEye,
      lucideEdit,
      lucideLoader2,
      lucidePhone,
      lucideFileText,
      monoClipboardCheck,
      remixFeedbackLine,
      monoPause,
      lucideXCircle,
      bootstrapGraphUp,
      bootstrapLink,
      monoCreditCard,
      bootstrapTicketPerforated,
      lucideChevronRight,
      lucideChevronsRight,
      lucideChevronLeft,
      lucideChevronsLeft,
      remixSuitcase2Line,
      lucidePlus,
      bootstrapArrowLeft,
      lucideRefreshCcw,
      bootstrapLockFill,
      lucideCopy,
      bootstrapCloudUpload,
      bootstrapFileEarmarkWordFill,
      lucideContact,
      lucideLink,
      lucideLockKeyhole,
      lucideFileUser,
      remixPixFill,
      bootstrapWhatsapp,
      bootstrapMusicNoteBeamed,
      lucideYoutube,
      lucideDownload,
      bootstrapCheckCircleFill,
    }),

    provideEnvironmentNgxMask(),
    provideNgxMask(),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideCharts(withDefaultRegisterables()),
  ],
};
