services:
  rencard-next:
    build:
      context: .
      dockerfile: Dockerfile
      target: next-runtime
    restart: unless-stopped

  rencard-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "3000:80"
    depends_on:
      - rencard-next
    restart: unless-stopped
