server {

    listen 80;
    server_name _;


    # Angular
    location = /app {
        return 302 /app/;
    }


    location /app/ {

        alias /usr/share/nginx/html/app/;

        try_files $uri $uri/ /app/index.html;
    }


    # Next assets
    location /_next/ {

        proxy_pass http://127.0.0.1:3000;

        proxy_set_header Host $host;
    }


    # Next
    location / {

        proxy_pass http://127.0.0.1:3000;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}